print("Welcome to the Interactive Personal Data Collector!!!")
name=input("Enter your name: ")
age=int(input("Enter your age: "))
height=float(input("Enter your height: "))
number=input("Enter your favorite number: ")
print("\nThank you. We have collected you data and it is as below. \n")
print(f"Name: {name} (Type: {type(name)}, Memory Address: {id(name)})")
print(f"Age: {age} (Type: {type(age)}, Memory Address: {id(age)})")
print(f"Height: {height} (Type: {type(height)}, Memory Address: {id(height)})")
print(f"Favorite number: {number} (Type: {type(number)}, Memory Address: {id(number)})")
print(f"\nYour birth year is approximately {2026-age}")
print("\nThank you for using Interactive Personal Data Collector and Have a VERY GOOD DAY!")